version: '1'

services:
  web:
    build: .
    container_name: ppshein-express
    depends_on:
      - mysqlDB
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      MYSQL_HOST : ppshein-mysql
    networks:
      - my-bridge-network

  mysqlDB:
    image: mysql:latest
    container_name: ppshein-mysql
    expose:
      - "3306"
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - .env
    networks:
      - my-bridge-network

networks:
  my-bridge-network:
    driver: bridge
